##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Sat Apr 11 18:50:23 CEST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = airnet_co2_fw


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og -Wextra -Werror


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32u0xx_it.c \
Core/Src/stm32u0xx_hal_msp.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_adc.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_adc_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_ll_adc.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_rcc.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_rcc_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_flash.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_flash_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_gpio.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_dma.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_dma_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_pwr.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_pwr_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_cortex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_exti.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_i2c.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_i2c_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_ll_i2c.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_rtc.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_rtc_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_spi.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_spi_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_tim.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_tim_ex.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_uart.c \
Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_uart_ex.c \
Core/Src/system_stm32u0xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c

C_SOURCES += Core/Src/skin.c
C_SOURCES += Core/Src/menu.c

C_SOURCES += Core/Src/sensirion_i2c_hal.c embedded-i2c-stcc4/sensirion_common.c embedded-i2c-stcc4/sensirion_i2c.c embedded-i2c-stcc4/stcc4_i2c.c

C_SOURCES += Drivers/EPD/EPD_1in54_V2.c Drivers/EPD/GUI_Paint.c
C_SOURCES += Drivers/EPD/Fonts/jfont12.c
C_SOURCES += Drivers/EPD/Fonts/font20.c
C_SOURCES += Drivers/EPD/Fonts/Digits25NotoSansSemiCondensedBold.c
C_SOURCES += Drivers/EPD/Fonts/Digits50NotoSansSemiCondensedBold.c
C_SOURCES += Drivers/EPD/Fonts/Digits90NotoSansSemiCondensedBold.c
C_SOURCES += Drivers/EPD/Fonts/Airnet40NotoSansSemiCondensedBoldItalic.c
C_SOURCES += Drivers/EPD/Fonts/CO253NotoSansExtraBold.c
C_SOURCES += Drivers/EPD/Fonts/CO2ppm25NotoSansMedium.c
C_SOURCES += Drivers/EPD/Fonts/Thermometer50Regular.c
C_SOURCES += Drivers/EPD/Fonts/Droplet20Regular.c
C_SOURCES += Drivers/EPD/Fonts/Lightning27Regular.c

# ASM sources
ASM_SOURCES =  \
startup_stm32u031xx.s

# ASMM sources
ASMM_SOURCES = 

# ASMMC sources
ASMMC_SOURCE = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0plus

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32U031xx

VERSION := \"$(shell git describe --always)\"
C_DEFS += -DVERSION="$(VERSION)"

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32U0xx_HAL_Driver/Inc \
-IDrivers/STM32U0xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32U0xx/Include \
-IDrivers/CMSIS/Include

C_INCLUDES += -Iembedded-i2c-stcc4/
C_INCLUDES += -IDrivers/EPD

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32U031xx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMMC_SOURCES:.c=.o)))
vpath %.S $(sort $(dir $(ASMMC_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	

$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
