/* File automatically generated by font2bytes */
/* font2bytes.py --ttf-input-file ./fonts/Noto_Emoji/NotoEmoji-Regular.ttf --height 30 --variable-width --font-name BatteryLow28 --format jFont --ascii-range 129707 -b tmp --y-offset -2 --cut-bottom 2 --x-offset -9 --cut-right 17 -o ../airnet_co2/Drivers/EPD/Fonts/BatteryLow28regular.c */

#include "jfonts.h"

static const uint8_t fontTable129707[] = 
{
	/* ASCII: 129707 "🪫" (16 pixels wide) */
	0x00, 0x00, 0x0f, 
	0xf0, 0x3e, 0x7c, 
	0x64, 0x26, 0x43, 
	0xc2, 0x40, 0x02, 
	0x60, 0x06, 0x78, 
	0x1e, 0x4f, 0xf2, 
	0x40, 0x02, 0x40, 
	0x02, 0x41, 0x82, 
	0x41, 0x82, 0x47, 
	0xe2, 0x41, 0x82, 
	0x41, 0x82, 0x40, 
	0x02, 0x40, 0x02, 
	0x4f, 0xf2, 0x5f, 
	0xfa, 0x5f, 0xfa, 
	0x5f, 0xfa, 0x58, 
	0x1a, 0x5c, 0x3a, 
	0x67, 0xf6, 0x38, 
	0x1c, 0x0f, 0xf0, 
	0x00, 0x00, 
};

jFont BatteryLow28 = {
	.max_width = 16, /* Maximum width */
	.height = 28, /* Height */
	.default_char = 'B', /* Default: '🪫' */
	.min_char = 'B', /* Min: '🪫' */
	.max_char = 'B', /* Max: '🪫' */
	.nb_glyphs = 1,
	.glyphs = {
		{
			.c = 'B', /* '🪫' */
			.width = 16,
			.table = fontTable129707,
		},
	}
};

