/* File automatically generated by font2bytes */
/* font2bytes.py --ttf-input-file ./fonts/NotoSansSymbols2-Regular.ttf --height 25 --variable-width --font-name Droplet20 --format jFont --ascii-range 127778 -b tmp --y-offset -5 --cut-bottom 5 -o ../airnet_co2/Drivers/EPD/Fonts/Droplet20Regular.c */

#include "jfonts.h"

static const uint8_t fontTable127778[] = 
{
	/* ASCII: 127778 "🌢" (14 pixels wide) */
	0x00, 0x00, 0x01, 
	0x00, 0x03, 0x00, 
	0x03, 0x80, 0x07, 
	0x80, 0x0f, 0xc0, 
	0x0f, 0xe0, 0x17, 
	0xe0, 0x37, 0xf0, 
	0x2f, 0xf0, 0x2f, 
	0xf8, 0x6f, 0xf8, 
	0x7f, 0xf8, 0x7f, 
	0xf8, 0x7f, 0xf8, 
	0x3f, 0xf8, 0x3f, 
	0xf0, 0x1f, 0xe0, 
	0x07, 0xc0, 0x00, 
	0x00, 
};

jFont Droplet20 = {
	.max_width = 14, /* Maximum width */
	.height = 20, /* Height */
	.default_char = 'D', /* Default: '🌢' */
	.min_char = 'D', /* Min: '🌢' */
	.max_char = 'D', /* Max: '🌢' */
	.nb_glyphs = 1,
	.glyphs = {
		{
			.c = 'D', /* '🌢' */
			.width = 14,
			.table = fontTable127778,
		},
	}
};

