/* File automatically generated by font2bytes */
/* font2bytes.py --ttf-input-file ./fonts/NotoSansSymbols2-Regular.ttf --height 30 --width 14 --font-name Lightning27 --format jFont --ascii-range 128498 -b tmp --y-offset -5 --cut-bottom 3 -o ../airnet_co2/Drivers/EPD/Fonts/Lightning27Regular.c */

#include "jfonts.h"

static const uint8_t fontTable128498[] = 
{
	/* ASCII: 128498 "🗲" (14 pixels wide) */
	0x00, 0x00, 0x00, 
	0x00, 0x00, 0x08, 
	0x00, 0x10, 0x00, 
	0x30, 0x00, 0x60, 
	0x00, 0xe0, 0x01, 
	0xc0, 0x03, 0x80, 
	0x07, 0x80, 0x0f, 
	0x00, 0x1f, 0xc0, 
	0x3f, 0xf0, 0x7f, 
	0xfc, 0x1f, 0xf8, 
	0x07, 0xf0, 0x03, 
	0xe0, 0x03, 0xc0, 
	0x07, 0x80, 0x07, 
	0x00, 0x0e, 0x00, 
	0x0c, 0x00, 0x18, 
	0x00, 0x30, 0x00, 
	0x20, 0x00, 0x40, 
	0x00, 0x00, 0x00, 
	
};

jFont Lightning27 = {
	.max_width = 14, /* Maximum width */
	.height = 27, /* Height */
	.default_char = 'L', /* Default: '🗲' */
	.min_char = 'L', /* Min: '🗲' */
	.max_char = 'L', /* Max: '🗲' */
	.nb_glyphs = 1,
	.glyphs = {
		{
			.c = 'L', /* '🗲' */
			.width = 14,
			.table = fontTable128498,
		},
	}
};

